### ISSUE TITLE
[feature suggestion] its better to have a props to check between 2 strings

### ISSUE THREAD

**Issue by darrylsepeda** [lannex/react-password-strength-bar#15]
I was thinking to put this bar on password and confirm password field, but when user fill in the confirm password field, the bar doesn't show whether the value is same with password.

So I suggest to add one property to handle this, and show the message like "Your confirm password is not same with your password".

**Comment by lannex** [comment]
Good suggestion. but I want to use this package simple. i think you can handle that using two states and one html element if i understand your situation.
