### ISSUE TITLE
React 17

### ISSUE THREAD

**Issue by pyronico** [lannex/react-password-strength-bar#33]
Hello, is it possible to use this package with react 17 ?

**Comment by lannex** [comment]
Of course. if you look at the example folder, it uses version 17.

**Comment by pyronico** [comment]
Are you sure? Because when I install the package, it came with react-Dom 16
dependency and break my application running with react 17.
May be you just need to update the package.Json of your package. I see
react 17 only on dev dependencies!

Thanks in advance

**Comment by pyronico** [comment]
I take about following peer dependencies "peerDependencies": { "react":
"^16.8.6", "react-dom": "^16.8.6" },
I think (I am not an expert), this few lines will import some react 16
dependecies in a react 17 and cause conflicts with react-Dom.


Le mer. 21 juil. 2021 à 23:00, Nicolas Pasquet ***@***.***> a
écrit :

**Comment by lannex** [comment]
@pyronico 
I tried again after your comment.

There was only a warning when I installed using yarn.
But it didn't go as you said when I installed using npm and I had to use '--force' or '--legacy-peer-deps' together.
(I have mainly used yarn.)

As you pointed out, this was a matter of version range of peer dependencies. I'll fix this problem.
Thank you.
