### ISSUE TITLE
Code splitting

### ISSUE THREAD

**Issue by rick427** [lannex/react-password-strength-bar#40]
How can i code split this package on CRA. I just read the react docs and it seems that you can but when i try it, i get errors (**JSX element type 'PasswordStrengthBar' does not have any construct or call signatures**.). This is what am doing below.

```js
import React from 'react';

const PasswordStrengthBar =  await import('react-password-strength-bar');

const PasswordReset:React.FC = () => {
    return (
        <div style={{margin: '2rem', width: '20rem'}}>
            <PasswordStrengthBar />
        </div>
    )
}

export default PasswordReset;
```

**Comment by lannex** [comment]
It will be easy for you to understand when you read this. 

https://reactjs.org/docs/code-splitting.html#reactlazy
