### ISSUE TITLE
minLength props does not seem to have any effect

### ISSUE THREAD

**Issue by vtrphan** [lannex/react-password-strength-bar#42]
The `minLength` prop doesn't seem to have any effect. The first red bar always only appears when the password length is >= 4.  Please check?

**Comment by yearnings** [comment]
Doesn't replicate for me – just updated from 4 to 8 with no issues.

What's it do with string `aaaa`? `minLength` nonwithstanding, that password is poor enough that the red bar shoudn't appear (there is a hidden level between the red bar and too short)

**Comment by lannex** [comment]
`minLength` is a kind of starting point. 
If it is less than this value, the message will only show `shortScoreWord`.
Each default is `4` and `too short`.
